export const ROLES = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  PHARMACIST: 'PHARMACIST',
  CASHIER: 'CASHIER',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
};

export const PERMISSIONS = {
  // Dashboard
  VIEW_DASHBOARD: [ROLES.ADMIN, ROLES.MANAGER, ROLES.PHARMACIST, ROLES.CASHIER, ROLES.INVENTORY_MANAGER],
  
  // POS
  ACCESS_POS: [ROLES.ADMIN, ROLES.MANAGER, ROLES.PHARMACIST, ROLES.CASHIER],
  
  // Products
  VIEW_PRODUCTS: [ROLES.ADMIN, ROLES.MANAGER, ROLES.PHARMACIST, ROLES.INVENTORY_MANAGER],
  CREATE_PRODUCT: [ROLES.ADMIN, ROLES.MANAGER],
  EDIT_PRODUCT: [ROLES.ADMIN, ROLES.MANAGER],
  DELETE_PRODUCT: [ROLES.ADMIN],
  
  // Inventory
  VIEW_INVENTORY: [ROLES.ADMIN, ROLES.MANAGER, ROLES.INVENTORY_MANAGER, ROLES.PHARMACIST],
  MANAGE_INVENTORY: [ROLES.ADMIN, ROLES.MANAGER, ROLES.INVENTORY_MANAGER],
  
  // Purchase Orders
  VIEW_PURCHASE_ORDERS: [ROLES.ADMIN, ROLES.MANAGER, ROLES.INVENTORY_MANAGER],
  CREATE_PURCHASE_ORDER: [ROLES.ADMIN, ROLES.MANAGER, ROLES.INVENTORY_MANAGER],
  APPROVE_PURCHASE_ORDER: [ROLES.ADMIN, ROLES.MANAGER],
  
  // GRN
  VIEW_GRN: [ROLES.ADMIN, ROLES.MANAGER, ROLES.INVENTORY_MANAGER],
  CREATE_GRN: [ROLES.ADMIN, ROLES.MANAGER, ROLES.INVENTORY_MANAGER],
  
  // Sales
  VIEW_SALES: [ROLES.ADMIN, ROLES.MANAGER],
  
  // Customers
  VIEW_CUSTOMERS: [ROLES.ADMIN, ROLES.MANAGER, ROLES.PHARMACIST, ROLES.CASHIER],
  MANAGE_CUSTOMERS: [ROLES.ADMIN, ROLES.MANAGER, ROLES.PHARMACIST],
  
  // Suppliers
  VIEW_SUPPLIERS: [ROLES.ADMIN, ROLES.MANAGER, ROLES.INVENTORY_MANAGER],
  MANAGE_SUPPLIERS: [ROLES.ADMIN, ROLES.MANAGER],
  
  // Users
  VIEW_USERS: [ROLES.ADMIN, ROLES.MANAGER],
  MANAGE_USERS: [ROLES.ADMIN],
  
  // Branches
  VIEW_BRANCHES: [ROLES.ADMIN, ROLES.MANAGER],
  MANAGE_BRANCHES: [ROLES.ADMIN],
};

export const hasPermission = (userRole, permission) => {
  return PERMISSIONS[permission]?.includes(userRole) || false;
};

export const canAccessRoute = (userRole, route) => {
  const routePermissions = {
    '/': 'VIEW_DASHBOARD',
    '/pos': 'ACCESS_POS',
    '/products': 'VIEW_PRODUCTS',
    '/categories': 'VIEW_PRODUCTS',
    '/inventory': 'VIEW_INVENTORY',
    '/purchase-orders': 'VIEW_PURCHASE_ORDERS',
    '/grn': 'VIEW_GRN',
    '/sales': 'VIEW_SALES',
    '/sale-returns': 'ACCESS_POS',
    '/customers': 'VIEW_CUSTOMERS',
    '/suppliers': 'VIEW_SUPPLIERS',
    '/users': 'VIEW_USERS',
    '/branches': 'VIEW_BRANCHES',
  };
  
  const permission = routePermissions[route];
  return permission ? hasPermission(userRole, permission) : false;
};
