// Auth Constants

/**
 * User roles in the system
 */
export const ROLES = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  PHARMACIST: 'PHARMACIST',
  CASHIER: 'CASHIER',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  BRANCH_MANAGER: 'BRANCH_MANAGER',
  EMPLOYEE: 'EMPLOYEE',
};

/**
 * Role hierarchy - higher index = more permissions
 */
export const ROLE_HIERARCHY = [
  ROLES.EMPLOYEE,
  ROLES.CASHIER,
  ROLES.INVENTORY_MANAGER,
  ROLES.PHARMACIST,
  ROLES.BRANCH_MANAGER,
  ROLES.MANAGER,
  ROLES.ADMIN,
];

/**
 * Permission definitions
 */
export const PERMISSIONS = {
  // Dashboard
  VIEW_DASHBOARD: [ROLES.ADMIN, ROLES.MANAGER, ROLES.PHARMACIST, ROLES.CASHIER, ROLES.INVENTORY_MANAGER, ROLES.BRANCH_MANAGER],
  
  // POS
  ACCESS_POS: [ROLES.ADMIN, ROLES.MANAGER, ROLES.PHARMACIST, ROLES.CASHIER],
  
  // Products
  VIEW_PRODUCTS: [ROLES.ADMIN, ROLES.MANAGER, ROLES.PHARMACIST, ROLES.INVENTORY_MANAGER],
  CREATE_PRODUCT: [ROLES.ADMIN, ROLES.MANAGER],
  EDIT_PRODUCT: [ROLES.ADMIN, ROLES.MANAGER],
  DELETE_PRODUCT: [ROLES.ADMIN],
  
  // Categories
  VIEW_CATEGORIES: [ROLES.ADMIN, ROLES.MANAGER, ROLES.PHARMACIST, ROLES.INVENTORY_MANAGER],
  MANAGE_CATEGORIES: [ROLES.ADMIN, ROLES.MANAGER],
  
  // Inventory
  VIEW_INVENTORY: [ROLES.ADMIN, ROLES.MANAGER, ROLES.INVENTORY_MANAGER, ROLES.PHARMACIST],
  MANAGE_INVENTORY: [ROLES.ADMIN, ROLES.MANAGER, ROLES.INVENTORY_MANAGER],
  
  // Purchase Orders
  VIEW_PURCHASE_ORDERS: [ROLES.ADMIN, ROLES.MANAGER, ROLES.INVENTORY_MANAGER],
  CREATE_PURCHASE_ORDER: [ROLES.ADMIN, ROLES.MANAGER, ROLES.INVENTORY_MANAGER],
  APPROVE_PURCHASE_ORDER: [ROLES.ADMIN, ROLES.MANAGER],
  
  // GRN
  VIEW_GRN: [ROLES.ADMIN, ROLES.MANAGER, ROLES.INVENTORY_MANAGER],
  CREATE_GRN: [ROLES.ADMIN, ROLES.MANAGER, ROLES.INVENTORY_MANAGER],
  
  // Sales
  VIEW_SALES: [ROLES.ADMIN, ROLES.MANAGER, ROLES.BRANCH_MANAGER],
  CREATE_SALE: [ROLES.ADMIN, ROLES.MANAGER, ROLES.CASHIER, ROLES.PHARMACIST],
  
  // Sale Returns
  VIEW_SALE_RETURNS: [ROLES.ADMIN, ROLES.MANAGER],
  CREATE_SALE_RETURN: [ROLES.ADMIN, ROLES.MANAGER, ROLES.CASHIER],
  
  // Customers
  VIEW_CUSTOMERS: [ROLES.ADMIN, ROLES.MANAGER, ROLES.PHARMACIST, ROLES.CASHIER],
  MANAGE_CUSTOMERS: [ROLES.ADMIN, ROLES.MANAGER, ROLES.PHARMACIST],
  
  // Suppliers
  VIEW_SUPPLIERS: [ROLES.ADMIN, ROLES.MANAGER, ROLES.INVENTORY_MANAGER],
  MANAGE_SUPPLIERS: [ROLES.ADMIN, ROLES.MANAGER],
  
  // Reports
  VIEW_REPORTS: [ROLES.ADMIN, ROLES.MANAGER, ROLES.BRANCH_MANAGER],
  EXPORT_REPORTS: [ROLES.ADMIN, ROLES.MANAGER],
  
  // Users
  VIEW_USERS: [ROLES.ADMIN, ROLES.MANAGER],
  MANAGE_USERS: [ROLES.ADMIN],
  
  // Branches
  VIEW_BRANCHES: [ROLES.ADMIN, ROLES.MANAGER],
  MANAGE_BRANCHES: [ROLES.ADMIN],
  
  // Settings
  VIEW_SETTINGS: [ROLES.ADMIN, ROLES.MANAGER],
  MANAGE_SETTINGS: [ROLES.ADMIN],
  
  // Audit Logs
  VIEW_AUDIT_LOGS: [ROLES.ADMIN],
  
  // Prescriptions (Pharmacist specific)
  VIEW_PRESCRIPTIONS: [ROLES.ADMIN, ROLES.MANAGER, ROLES.PHARMACIST],
  MANAGE_PRESCRIPTIONS: [ROLES.PHARMACIST],
  
  // Staff Management (Branch Manager specific)
  VIEW_STAFF: [ROLES.ADMIN, ROLES.MANAGER, ROLES.BRANCH_MANAGER],
  MANAGE_STAFF: [ROLES.ADMIN, ROLES.MANAGER, ROLES.BRANCH_MANAGER],
  
  // Attendance & Leave (Employee specific)
  VIEW_ATTENDANCE: [ROLES.ADMIN, ROLES.MANAGER, ROLES.BRANCH_MANAGER, ROLES.EMPLOYEE],
  MANAGE_ATTENDANCE: [ROLES.ADMIN, ROLES.MANAGER, ROLES.BRANCH_MANAGER],
  REQUEST_LEAVE: [ROLES.EMPLOYEE, ROLES.CASHIER, ROLES.PHARMACIST, ROLES.INVENTORY_MANAGER],
  APPROVE_LEAVE: [ROLES.ADMIN, ROLES.MANAGER, ROLES.BRANCH_MANAGER],
};

/**
 * Route permissions mapping
 */
export const ROUTE_PERMISSIONS = {
  '/': 'VIEW_DASHBOARD',
  '/pos': 'ACCESS_POS',
  '/products': 'VIEW_PRODUCTS',
  '/categories': 'VIEW_CATEGORIES',
  '/inventory': 'VIEW_INVENTORY',
  '/purchase-orders': 'VIEW_PURCHASE_ORDERS',
  '/grn': 'VIEW_GRN',
  '/sales': 'VIEW_SALES',
  '/sale-returns': 'VIEW_SALE_RETURNS',
  '/customers': 'VIEW_CUSTOMERS',
  '/suppliers': 'VIEW_SUPPLIERS',
  '/reports': 'VIEW_REPORTS',
  '/users': 'VIEW_USERS',
  '/branches': 'VIEW_BRANCHES',
  '/settings': 'VIEW_SETTINGS',
  '/audit-logs': 'VIEW_AUDIT_LOGS',
};

/**
 * Token configuration
 */
export const TOKEN_CONFIG = {
  ACCESS_TOKEN_KEY: 'token',
  REFRESH_TOKEN_KEY: 'refreshToken',
  USER_KEY: 'user',
  SELECTED_BRANCH_KEY: 'selectedBranch',
  TOKEN_EXPIRY_BUFFER: 5 * 60 * 1000, // 5 minutes before expiry
};

/**
 * Session configuration
 */
export const SESSION_CONFIG = {
  TIMEOUT_WARNING: 5 * 60 * 1000, // 5 minutes warning before timeout
  IDLE_TIMEOUT: 30 * 60 * 1000, // 30 minutes idle timeout
  MAX_SESSION_DURATION: 8 * 60 * 60 * 1000, // 8 hours max session
};

/**
 * Password requirements
 */
export const PASSWORD_REQUIREMENTS = {
  MIN_LENGTH: 8,
  MAX_LENGTH: 128,
  REQUIRE_UPPERCASE: true,
  REQUIRE_LOWERCASE: true,
  REQUIRE_NUMBER: true,
  REQUIRE_SPECIAL: false,
};
