/**
 * Notification Type - Matching backend NotificationType.java enum
 */
export const NOTIFICATION_TYPE = {
  LOW_STOCK: 'LOW_STOCK',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  EXPIRY_ALERT: 'EXPIRY_ALERT',
  EXPIRED: 'EXPIRED',
  NEW_ORDER: 'NEW_ORDER',
  ORDER_APPROVED: 'ORDER_APPROVED',
  ORDER_REJECTED: 'ORDER_REJECTED',
  TRANSFER_REQUEST: 'TRANSFER_REQUEST',
  TRANSFER_APPROVED: 'TRANSFER_APPROVED',
  PAYMENT_DUE: 'PAYMENT_DUE',
  SYSTEM: 'SYSTEM',
  INFO: 'INFO',
};

export const NOTIFICATION_TYPE_LABELS = {
  [NOTIFICATION_TYPE.LOW_STOCK]: 'Low Stock',
  [NOTIFICATION_TYPE.OUT_OF_STOCK]: 'Out of Stock',
  [NOTIFICATION_TYPE.EXPIRY_ALERT]: 'Expiry Alert',
  [NOTIFICATION_TYPE.EXPIRED]: 'Expired',
  [NOTIFICATION_TYPE.NEW_ORDER]: 'New Order',
  [NOTIFICATION_TYPE.ORDER_APPROVED]: 'Order Approved',
  [NOTIFICATION_TYPE.ORDER_REJECTED]: 'Order Rejected',
  [NOTIFICATION_TYPE.TRANSFER_REQUEST]: 'Transfer Request',
  [NOTIFICATION_TYPE.TRANSFER_APPROVED]: 'Transfer Approved',
  [NOTIFICATION_TYPE.PAYMENT_DUE]: 'Payment Due',
  [NOTIFICATION_TYPE.SYSTEM]: 'System',
  [NOTIFICATION_TYPE.INFO]: 'Information',
};

export const NOTIFICATION_TYPE_COLORS = {
  [NOTIFICATION_TYPE.LOW_STOCK]: 'bg-yellow-100 text-yellow-800',
  [NOTIFICATION_TYPE.OUT_OF_STOCK]: 'bg-red-100 text-red-800',
  [NOTIFICATION_TYPE.EXPIRY_ALERT]: 'bg-orange-100 text-orange-800',
  [NOTIFICATION_TYPE.EXPIRED]: 'bg-red-200 text-red-900',
  [NOTIFICATION_TYPE.NEW_ORDER]: 'bg-blue-100 text-blue-800',
  [NOTIFICATION_TYPE.ORDER_APPROVED]: 'bg-green-100 text-green-800',
  [NOTIFICATION_TYPE.ORDER_REJECTED]: 'bg-red-100 text-red-800',
  [NOTIFICATION_TYPE.TRANSFER_REQUEST]: 'bg-purple-100 text-purple-800',
  [NOTIFICATION_TYPE.TRANSFER_APPROVED]: 'bg-green-100 text-green-800',
  [NOTIFICATION_TYPE.PAYMENT_DUE]: 'bg-orange-100 text-orange-800',
  [NOTIFICATION_TYPE.SYSTEM]: 'bg-gray-100 text-gray-800',
  [NOTIFICATION_TYPE.INFO]: 'bg-cyan-100 text-cyan-800',
};

export const NOTIFICATION_TYPE_ICONS = {
  [NOTIFICATION_TYPE.LOW_STOCK]: 'AlertTriangle',
  [NOTIFICATION_TYPE.OUT_OF_STOCK]: 'XCircle',
  [NOTIFICATION_TYPE.EXPIRY_ALERT]: 'Clock',
  [NOTIFICATION_TYPE.EXPIRED]: 'AlertOctagon',
  [NOTIFICATION_TYPE.NEW_ORDER]: 'ShoppingCart',
  [NOTIFICATION_TYPE.ORDER_APPROVED]: 'CheckCircle',
  [NOTIFICATION_TYPE.ORDER_REJECTED]: 'XCircle',
  [NOTIFICATION_TYPE.TRANSFER_REQUEST]: 'ArrowRightLeft',
  [NOTIFICATION_TYPE.TRANSFER_APPROVED]: 'CheckCircle',
  [NOTIFICATION_TYPE.PAYMENT_DUE]: 'DollarSign',
  [NOTIFICATION_TYPE.SYSTEM]: 'Settings',
  [NOTIFICATION_TYPE.INFO]: 'Info',
};
