/**
 * Stock Movement Type - Matching backend StockMovementType.java enum
 */
export const STOCK_MOVEMENT_TYPE = {
  PURCHASE: 'PURCHASE',
  SALE: 'SALE',
  SALE_RETURN: 'SALE_RETURN',
  PURCHASE_RETURN: 'PURCHASE_RETURN',
  TRANSFER_IN: 'TRANSFER_IN',
  TRANSFER_OUT: 'TRANSFER_OUT',
  ADJUSTMENT_IN: 'ADJUSTMENT_IN',
  ADJUSTMENT_OUT: 'ADJUSTMENT_OUT',
  EXPIRED: 'EXPIRED',
  DAMAGED: 'DAMAGED',
  OPENING_STOCK: 'OPENING_STOCK',
};

export const STOCK_MOVEMENT_TYPE_LABELS = {
  [STOCK_MOVEMENT_TYPE.PURCHASE]: 'Purchase',
  [STOCK_MOVEMENT_TYPE.SALE]: 'Sale',
  [STOCK_MOVEMENT_TYPE.SALE_RETURN]: 'Sale Return',
  [STOCK_MOVEMENT_TYPE.PURCHASE_RETURN]: 'Purchase Return',
  [STOCK_MOVEMENT_TYPE.TRANSFER_IN]: 'Transfer In',
  [STOCK_MOVEMENT_TYPE.TRANSFER_OUT]: 'Transfer Out',
  [STOCK_MOVEMENT_TYPE.ADJUSTMENT_IN]: 'Adjustment In',
  [STOCK_MOVEMENT_TYPE.ADJUSTMENT_OUT]: 'Adjustment Out',
  [STOCK_MOVEMENT_TYPE.EXPIRED]: 'Expired',
  [STOCK_MOVEMENT_TYPE.DAMAGED]: 'Damaged',
  [STOCK_MOVEMENT_TYPE.OPENING_STOCK]: 'Opening Stock',
};

export const STOCK_MOVEMENT_TYPE_COLORS = {
  [STOCK_MOVEMENT_TYPE.PURCHASE]: 'bg-green-100 text-green-800',
  [STOCK_MOVEMENT_TYPE.SALE]: 'bg-blue-100 text-blue-800',
  [STOCK_MOVEMENT_TYPE.SALE_RETURN]: 'bg-yellow-100 text-yellow-800',
  [STOCK_MOVEMENT_TYPE.PURCHASE_RETURN]: 'bg-orange-100 text-orange-800',
  [STOCK_MOVEMENT_TYPE.TRANSFER_IN]: 'bg-cyan-100 text-cyan-800',
  [STOCK_MOVEMENT_TYPE.TRANSFER_OUT]: 'bg-purple-100 text-purple-800',
  [STOCK_MOVEMENT_TYPE.ADJUSTMENT_IN]: 'bg-teal-100 text-teal-800',
  [STOCK_MOVEMENT_TYPE.ADJUSTMENT_OUT]: 'bg-pink-100 text-pink-800',
  [STOCK_MOVEMENT_TYPE.EXPIRED]: 'bg-red-100 text-red-800',
  [STOCK_MOVEMENT_TYPE.DAMAGED]: 'bg-red-200 text-red-900',
  [STOCK_MOVEMENT_TYPE.OPENING_STOCK]: 'bg-gray-100 text-gray-800',
};

// Movement types that increase stock
export const STOCK_IN_TYPES = [
  STOCK_MOVEMENT_TYPE.PURCHASE,
  STOCK_MOVEMENT_TYPE.SALE_RETURN,
  STOCK_MOVEMENT_TYPE.TRANSFER_IN,
  STOCK_MOVEMENT_TYPE.ADJUSTMENT_IN,
  STOCK_MOVEMENT_TYPE.OPENING_STOCK,
];

// Movement types that decrease stock
export const STOCK_OUT_TYPES = [
  STOCK_MOVEMENT_TYPE.SALE,
  STOCK_MOVEMENT_TYPE.PURCHASE_RETURN,
  STOCK_MOVEMENT_TYPE.TRANSFER_OUT,
  STOCK_MOVEMENT_TYPE.ADJUSTMENT_OUT,
  STOCK_MOVEMENT_TYPE.EXPIRED,
  STOCK_MOVEMENT_TYPE.DAMAGED,
];

export const isStockIn = (type) => STOCK_IN_TYPES.includes(type);
export const isStockOut = (type) => STOCK_OUT_TYPES.includes(type);
